# Generated by Django 5.1.2 on 2025-08-11 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_profile_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('device', models.CharField(max_length=32)),
                ('browser', models.CharField(max_length=64)),
                ('use_case', models.CharField(max_length=200)),
                ('input_type', models.CharField(max_length=64)),
                ('ease', models.PositiveSmallIntegerField(default=3)),
                ('speed', models.PositiveSmallIntegerField(default=3)),
                ('accuracy', models.PositiveSmallIntegerField(default=3)),
                ('clarity', models.PositiveSmallIntegerField(default=3)),
                ('nps', models.PositiveSmallIntegerField()),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('bugs', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='beta_screens/')),
                ('allow_contact', models.BooleanField(default=False)),
                ('allow_anon', models.BooleanField(default=True)),
            ],
        ),
    ]
