# Generated by Django 5.1.2 on 2025-09-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_org_patient_encounter_orgmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organization Domain',
                'verbose_name_plural': 'Organization Domains',
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['org', 'status'], name='myApp_encou_org_id_89afc1_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['org', '-created_at'], name='myApp_encou_org_id_52064a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['org', 'last_name', 'first_name'], name='myApp_patie_org_id_c6a46a_idx'),
        ),
        migrations.AddField(
            model_name='orgdomain',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='myApp.org'),
        ),
    ]
