# Generated by Django 5.1.2 on 2025-09-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_orgdomain_encounter_myapp_encou_org_id_89afc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
