# Generated by Django 5.1.2 on 2025-09-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_profile_signup_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
