# Generated by Django 5.1.2 on 2025-09-16 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_profile_last_login_country_profile_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='lang',
            field=models.CharField(blank=True, default='en-US', max_length=10),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='tone',
            field=models.CharField(blank=True, default='PlainClinical', max_length=50),
        ),
    ]
