# Generated by Django 5.1.1 on 2025-10-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_chatsession_options_chatsession_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalsummary',
            name='care_setting',
            field=models.CharField(choices=[('hospital', 'Hospital/Discharge'), ('ambulatory', 'Ambulatory/Clinic'), ('urgent', 'Urgent Care')], db_index=True, default='hospital', max_length=16),
        ),
    ]
