# Generated by Django 5.1.2 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_medicalsummary_care_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signup',
                'verbose_name_plural': 'User Signups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('is_unique', models.BooleanField(default=True, help_text='First visit from this IP in 24 hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_visit_created_da043f_idx'), models.Index(fields=['ip_address', 'created_at'], name='myApp_visit_ip_addr_1e522c_idx'), models.Index(fields=['path', 'created_at'], name='myApp_visit_path_1db726_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSignin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signin_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signin',
                'verbose_name_plural': 'User Signins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_users_created_201586_idx'), models.Index(fields=['user', '-created_at'], name='myApp_users_user_id_ffefd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=0, help_text='Time spent on page in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='myApp.visitor')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_pagev_created_1a09db_idx'), models.Index(fields=['path', '-created_at'], name='myApp_pagev_path_dedfba_idx')],
            },
        ),
    ]
