# Generated by Django 5.1.2 on 2025-12-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_usersignup_visitor_usersignin_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('utm_source', models.CharField(max_length=100)),
                ('utm_medium', models.CharField(max_length=100)),
                ('utm_campaign', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='entry_page',
            field=models.BooleanField(default=False, help_text='Is this an entry page?'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='exit_page',
            field=models.BooleanField(default=False, help_text='Is this an exit page?'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referer',
            field=models.URLField(blank=True, help_text='Referrer URL'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='scroll_depth',
            field=models.IntegerField(default=0, help_text='Scroll percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='time_on_page',
            field=models.IntegerField(default=0, help_text='Time on page in seconds'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='browser',
            field=models.CharField(blank=True, help_text='Browser name (Chrome, Firefox, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(blank=True, help_text='Country code (e.g., US, UK)', max_length=2),
        ),
        migrations.AddField(
            model_name='visitor',
            name='device_type',
            field=models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='visitor',
            name='os',
            field=models.CharField(blank=True, help_text='Operating system', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Custom session identifier', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Session duration in seconds')),
                ('page_count', models.IntegerField(default=0, help_text='Number of pages viewed')),
                ('is_bounce', models.BooleanField(default=False, help_text='Single page visit')),
                ('referer', models.URLField(blank=True)),
                ('entry_page', models.CharField(blank=True, max_length=500)),
                ('exit_page', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='myApp.visitor')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='click, download, submit, etc.', max_length=50)),
                ('event_name', models.CharField(help_text='Name of the event', max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Additional event properties')),
                ('path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myApp.visitor')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.session')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at'], name='myApp_sessi_started_f6d8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_id'], name='myApp_sessi_session_dcc865_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='myApp_event_created_cea92f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-created_at'], name='myApp_event_event_t_8b02a2_idx'),
        ),
    ]
