# Generated by Django 4.2.11 on 2026-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_profile_referral_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_settings',
            field=models.JSONField(blank=True, default=dict, help_text='User settings: appearance, accent_color, spoken_language, voice, separate_voice_mode, show_additional_models, personalization, etc.'),
        ),
    ]
