# Generated by Django 4.2.11 on 2026-01-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0017_add_user_settings_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_customer_id',
            field=models.CharField(blank=True, help_text='PayPal customer ID (Payer ID)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('clinical', 'Clinical')], default='free', help_text="User's subscription plan", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription period ends', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('inactive', 'Inactive'), ('manual', 'Manual')], default='inactive', help_text='Current subscription status', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('clinical', 'Clinical')], max_length=20)),
                ('paypal_subscription_id', models.CharField(blank=True, help_text='PayPal subscription ID', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('inactive', 'Inactive'), ('manual', 'Manual')], default='inactive', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='When the current billing period ends', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(help_text='PayPal order ID', max_length=255, unique=True)),
                ('paypal_transaction_id', models.CharField(blank=True, help_text='PayPal transaction ID', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in USD', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('plan_id', models.CharField(help_text='Plan ID (monthly, annual, clinical)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='myApp.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-created_at'], name='myApp_subsc_user_id_3d0034_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='myApp_subsc_status_9f8a12_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='myApp_payme_user_id_19c0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='myApp_payme_status_410388_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paypal_order_id'], name='myApp_payme_paypal__eec3ef_idx'),
        ),
    ]
